// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAopLVnE4wA0c0GL3iMfONKVQPGJjbALnA',
    appId: '1:386163000740:web:ceb38afe0a65ccf16f2d31',
    messagingSenderId: '386163000740',
    projectId: 'film-tracker-database',
    authDomain: 'film-tracker-database.firebaseapp.com',
    storageBucket: 'film-tracker-database.appspot.com',
    measurementId: 'G-R5BSCEHX79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ8K90brEEkspVFTcC-l89bxvFgHnPy_0',
    appId: '1:386163000740:android:26fdc3c678b9e2266f2d31',
    messagingSenderId: '386163000740',
    projectId: 'film-tracker-database',
    storageBucket: 'film-tracker-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN10uqTHKL3S44JMKMdj6N2oeQxnNm144',
    appId: '1:386163000740:ios:935f9bf1c2d473ff6f2d31',
    messagingSenderId: '386163000740',
    projectId: 'film-tracker-database',
    storageBucket: 'film-tracker-database.appspot.com',
    iosBundleId: 'com.example.filmTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN10uqTHKL3S44JMKMdj6N2oeQxnNm144',
    appId: '1:386163000740:ios:654c184cfe44eb966f2d31',
    messagingSenderId: '386163000740',
    projectId: 'film-tracker-database',
    storageBucket: 'film-tracker-database.appspot.com',
    iosBundleId: 'com.example.filmTracker.RunnerTests',
  );
}
